keywords:
  - pendente
  - pendentes
  - lembrar
  - comprar
  - fazer
  - não esquecer
  - nao esquecer
  - tarefas
  - por fazer
  - temos de
  - tenho de
  - preciso de
  - devemos

prefixes:
  - tenho um pendente para
  - tenho um pendente de
  - pendente para
  - pendente de
  - lembrar de
  - lembrar para
  - não esquecer de
  - nao esquecer de
  - temos de
  - tenho de
  - preciso de
  - devemos
  
done:
  - feito
  - concluído
  - concluido
  - done
  - terminado
  - pronto
